### ISSUE TITLE
CMake error with add_lisp_executable

### ISSUE THREAD

**Issue by tprk77** [code-iai/roslisp_tutorials#1]
Hello! I am trying to build this tutorial in Indigo. It is not working. Basically, it looks like `add_lisp_executable` is missing or changed names.

```
-- +++ processing catkin package: 'roslisp_tutorials_basics'
-- ==> add_subdirectory(roslisp_tutorials/roslisp_tutorials_basics)
-- Using these message generators: gencpp;genlisp;genpy
-- roslisp_tutorials_basics: 2 messages, 1 services
CMake Error at roslisp_tutorials/roslisp_tutorials_basics/CMakeLists.txt:35 (add_lisp_executable):
  Unknown CMake command "add_lisp_executable".


-- Configuring incomplete, errors occurred!
```

**Comment by tprk77** [comment]
So I've realized these tutorials are probably not meant to work with Indigo. Do any official tutorials exist at this point? I'm trying to figure out how to build with Catkin.

**Comment by airballking** [comment]
Thanks for your interest! It's great to see people interested in using lisp for robot programming. :) `add_lisp_executable` is currently not working in catkin, that is correct. We're looking into this at the moment, and will try to have a working release in the midterm future (1-2 months).

In the meantime, you can try to go through these tutorials compiling everything in the repl. This is how we in Bremen are developing roslisp code.

**Comment by tprk77** [comment]
Ok. Thanks for the clarification!

**Comment by dongho-song** [comment]
Hello Mr.Airballking,
I am installing CRAM-system on Ubuntu 12.04, groovy ROS and knowrob because CRAM is only supporting groovy and hydro ROS. However, I am facing exactly the same catkin CMake problem with add_lisp_executable that tprk77 mentioned above.
I am wondering when your bug-fixed release version will come out ? 
I am going to use your CRAM system for this Spring term project in our graduate class.
Please let me know the available time and if possible raise the priority of the work in your group.
Thanks.

Dongho Song, Prof.
Dept. of Computer Engineering,
Korea Aerospace Univ.

**Comment by fairlight1337** [comment]
Dear @dongho-song,

thanks for your interest in the project(s). By now, we are running CRAM on ROS Indigo, so any compatibility problems that were hindering you in the past should be gone. This accounts for the source version to be downloaded from https://github.com/cram-code. If any incompatibilities come up, we'd be very grateful if you could point us towards them.

We'll discuss the `add_lisp_executable` problem and get back to this thread when the status changes.

Cheers,
Jan

**Comment by ClintLiddick** [comment]
Just a note for anyone who checks here, the latest version of http://github.com/ros/roslisp source (after ros/roslisp@41869c7d4aa50a854e28482f61ae8df7678f2f9f) provides the `add_lisp_executable` function, allowing these tutorials to be compiled via `catkin_make`.

**Comment by gaya-** [comment]
@airballking, we should get a new release at some point (if you didn't forget then sorry about the annoying reminder).

**Comment by airballking** [comment]
@gaya- @ClintLiddick Sorry for the long wait, guys! 

I just triggered the release of the newest version of `roslisp` for both `Indigo` and `Jade`. Should be there with the next release.

**Comment by gaya-** [comment]
Fixed with https://github.com/ros/roslisp/releases/tag/1.9.19 release.
